In [29]:
import logging
import pandas as pd
import numpy as np

logging.basicConfig(filename="26FebInfo.log", level=logging.INFO, format="%(asctime)s %(name)s %(message)s")     

In [30]:
# answer 1
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

"""
The data type of list_ is list and the data type of array_list is numpy.ndarray.
"""

<class 'list'>
<class 'numpy.ndarray'>


'\nThe data type of list_ is list and the data type of array_list is numpy.ndarray.\n'

In [31]:
# answer 2
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

logging.info("Print data type of each element in list_")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [32]:
# answer 3
array_list = np.array(object=list_, dtype=int)

# Yes, the dtype=int argument specifies that the elements in array_list should be cast as integers.
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

logging.info("Print data type of each element in list_")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [33]:
# answer 4
"""
To find the characteristics of variable num_array, we can use the following numpy methods:

shape: returns a tuple of integers representing the dimensions of the array.
size: returns the total number of elements in the array.
"""
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

logging.info("finding the shape of num_array")
print(num_array.shape)

logging.info("finding the size of num_array")
print(num_array.size)

(2, 3)
6


In [34]:
# answer 5
logging.info("Create a 3x3 array of zeros")
zeros_array = np.zeros(shape=(3, 3))

# Print the zeros_array
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
# answer 6
logging.info("Create a 5x5 identity matrix")
identity_matrix = np.eye(N=5, M=5)

# Print the identity_matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
